# Generated by Django 3.2.6 on 2021-09-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20210825_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_first_name',
            field=models.CharField(default='emma', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='default_last_name',
            field=models.CharField(default='harte', max_length=40),
            preserve_default=False,
        ),
    ]
