# Generated by Django 3.2.6 on 2021-08-29 10:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=254, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=254)),
                ('body', models.TextField(validators=[django.core.validators.MinLengthValidator(20)])),
                ('image', models.URLField(blank=True, max_length=1000, null=True)),
                ('keyword', models.ManyToManyField(blank=True, to='blog.Keyword')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
