# Generated by Django 3.2.6 on 2021-08-29 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210829_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='keyword',
            new_name='keywords',
        ),
    ]
