# Generated by Django 3.2.6 on 2021-09-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210901_0658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='user',
        ),
        migrations.AddField(
            model_name='reply',
            name='author',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reply',
            name='email',
            field=models.EmailField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
