# Generated by Django 3.2.6 on 2021-09-07 13:42

import ckeditor.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_blog_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='teaser',
            field=ckeditor.fields.RichTextField(validators=[django.core.validators.MinLengthValidator(70)]),
        ),
    ]
