# Generated by Django 3.2.6 on 2021-09-07 19:40

import ckeditor.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_blog_teaser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='email',
        ),
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=ckeditor.fields.RichTextField(default=' dsf sfsfsf sfdsdfsfs sdfsdf dfsfsdf sfsf d fsfs f sd fdf  ere r sf  fdf s sdf sdf sd sd e  rs  f f fs  re r s f s re ', validators=[django.core.validators.MinLengthValidator(70)]),
            preserve_default=False,
        ),
    ]
