# Generated by Django 3.2.6 on 2021-08-17 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='street_address1',
            new_name='address_line1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='street_address2',
            new_name='address_line2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone_number',
        ),
    ]
