# Generated by Django 3.2.6 on 2021-08-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20210817_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mobile_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
