# Generated by Django 3.2.6 on 2021-09-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('size', models.CharField(choices=[(' ', 'Canvas size *'), ('A5', 'A5'), ('A4', 'A4'), ('A2', 'A2'), ('A1', 'A1'), ('Not sure', 'Not sure')], default='Canvas size *', max_length=30)),
                ('pet_num', models.CharField(choices=[(' ', 'Number of Pets *'), ('1', '1'), ('2', '2'), ('3', '3')], default='Number of Pets *', max_length=30)),
                ('media', models.CharField(choices=[(' ', 'Media Preference *'), ('penil', 'Pencil'), ('Acrylic', 'Acrylic'), ('Watercolor', 'Watercolor'), ('Not sure', 'Not sure')], default='Media Preference *', max_length=40)),
                ('image', models.ImageField(upload_to='')),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
