# Generated by Django 3.2.6 on 2021-09-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissions',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
