# Generated by Django 3.2.6 on 2021-09-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_alter_commissions_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissions',
            name='media',
            field=models.CharField(choices=[('', 'Media Preference *'), ('penil', 'Pencil'), ('Acrylic', 'Acrylic'), ('Watercolor', 'Watercolor'), ('Not sure', 'Not sure')], default='Media Preference *', max_length=40),
        ),
        migrations.AlterField(
            model_name='commissions',
            name='pet_num',
            field=models.CharField(choices=[('', 'Number of Pets *'), ('1', '1'), ('2', '2'), ('3', '3')], default='Number of Pets *', max_length=30),
        ),
        migrations.AlterField(
            model_name='commissions',
            name='size',
            field=models.CharField(choices=[('', 'Canvas size *'), ('A5', 'A5'), ('A4', 'A4'), ('A2', 'A2'), ('A1', 'A1'), ('Not sure', 'Not sure')], default='Canvas size *', max_length=30),
        ),
    ]
