# Generated by Django 3.2.6 on 2022-02-06 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0004_commissions_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commissions',
            options={'verbose_name_plural': 'Commissions'},
        ),
    ]
