# Generated by Django 3.2.6 on 2021-09-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productreview_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='review_rating',
            field=models.CharField(choices=[(' ', 'Your rating'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=' ', max_length=1, null=True),
        ),
    ]
