# Generated by Django 3.2.6 on 2021-09-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review_rating',
            field=models.CharField(choices=[('', 'Rating *'), ('1', '1'), (
                '2', '2'), ('3', '3'), ('4', '4'), (
                    '5', '5')], default='Rating *', max_length=10),
        ),
    ]
