# Generated by Django 3.2.6 on 2021-09-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210915_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='media',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(max_length=100),
        ),
    ]
