# Generated by Django 3.2.6 on 2021-09-16 06:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20210915_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='media',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MaxValueValidator(200)]),
        ),
    ]
